apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: springboot
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
        - name: dockerpullsecret
      containers:
      - name: nginx
        image: 100.125.7.25:20202/tseye-docker-registry/nginx:latest
        ports:
        - containerPort: 80
